Remove assert statement from non-test files
tensorflow/tfx pull request #5369
Opened 2022-10-13 23:47 UTC by harishsg993010

2022-10-14 19:23 UTC, gbaned commented
@harishsg993010 Can you please sign CLA. Thank you!

2022-11-12 14:42 UTC, gbaned commented
@harishsg993010 Any update on this PR? Please. Thank you!

2022-11-15 08:52 UTC, chongkong requested changes
Sorry I was reviewing this PR old time ago but I had a 500 error at Github (and some of my comments not saved 😂) at the time and then didn't come back for a while.

2022-11-15 08:52 UTC, chongkong commented on tfx/components/trainer/rewriting/rewriter_test.py
> +      if original_model != self._expected_original_model:
This is a test file so assert is okay

2022-11-15 08:52 UTC, chongkong commented on tfx/components/transform/executor.py
> +    if not self._file_pattern:
Please avoid using empty error message (fill with some message.)

2022-11-15 08:52 UTC, chongkong commented on tfx/components/transform/executor.py
> +          examples_file_formats):
please fix line break

2022-11-15 08:52 UTC, chongkong commented on tfx/components/transform/executor.py
> +      if len(data_uris) != len(
please fix line break

2022-11-15 08:52 UTC, chongkong commented on tfx/components/transform/executor.py
> +      if not (datasets[0].tfxio.ArrowSchema().equals(
unnecessary parenthesis

2022-11-15 08:52 UTC, chongkong commented on tfx/components/transform/executor_test.py
> +        raise AssertionError
this is a test file so assert should be okay. please revert.

2022-11-15 08:52 UTC, chongkong commented on tfx/types/value_artifact_test.py
> +      raise AssertionError(value)
this is a test file so should be okay. please revert

2022-11-15 08:52 UTC, chongkong commented on tfx/utils/typing_utils.py
> +        raise AssertionError
please give a descriptive error message. same for the below.

2022-11-24 22:56 UTC, gbaned commented
@harishsg993010 Can you please sign CLA. Thank you!

2022-12-16 13:42 UTC, gbaned commented
Hi @harishsg993010 Any update on this PR? Please. Thank you!

2023-02-02 02:02 UTC, closed without merging