Update standard_artifacts.py
tensorflow/tfx pull request #6546
Opened 2024-01-02 04:19 UTC by anonymousdouble

refactor with fstring to format string to make code more Pythonic.

2024-01-02 06:38 UTC, gbaned commented
Hi @anonymousdouble Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.

The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.

For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/

Thank you for your contribution!

2024-01-03 08:37 UTC, gbaned commented
Hi @anonymousdouble Can you please fix the build [failures](https://github.com/tensorflow/tfx/actions/runs/7384229421/job/20087393096?pr=6546). Thank you!

![image](https://github.com/tensorflow/tfx/assets/48215717/96e75ecb-cc67-49d3-8468-5aa38b0f0078)

2024-01-04 04:47 UTC, roseayeon approved these changes
The CI Python version has been updated to 3.9. However, unrelated changes are causing the build to fail. As these changes are unrelated, I'll approve this PR.

2024-01-05 08:09 UTC, gbaned approved these changes

2024-01-10 05:44 UTC, chongkong requested changes

2024-01-10 05:44 UTC, chongkong commented on tfx/types/standard_artifacts.py
> +      raise TypeError(f'Expecting bytes but got value {str(value)} of type {type(value)}')
`str(x)` is unnecessary; just use `x`. Same for others.

2024-01-17 06:58 UTC, gbaned commented
Hi @anonymousdouble Can you please check @chongkong's comments and keep us posted ? Thank you!

2024-01-24 05:23 UTC, roseayeon approved these changes

2024-01-24 08:05 UTC, merged